services:
  - type: web
    name: arogya360
    env: docker
    plan: free
    branch: main
    envVars:
      - key: DB_URL
        value: jdbc:postgresql://dpg-d8pg02rsq97s7382eh40-a.oregon-postgres.render.com:5432/hospital_db
      - key: DB_USERNAME
        value: hospital_user
      - key: DB_PASSWORD
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: PORT
        value: 8081
